<a href="https://colab.research.google.com/github/siddharth-ranjan/Colab-Notebooks/blob/main/ANN_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116


In [2]:
import torch
print(torch.__version__)  # Check the installed version

# Optional: Check GPU availability if applicable
if torch.cuda.is_available():
    print("CUDA is available")


2.1.0+cu121


In [3]:
# import basic libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
data = pd.read_csv('/content/Churn_Modelling.csv')

In [5]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
data.shape

(10000, 14)

In [7]:

X = data.iloc[:, 3:13]
y = data.iloc[:, 13]

In [8]:
# Feature eng
geography = pd.get_dummies(X['Geography'], drop_first = True)
geography.head()

Germany  Spain
0        0      0
1        0      1
2        0      0
3        0      0
4        0      1

In [9]:
gender = pd.get_dummies(X['Gender'], drop_first=True)
gender.head()

Male
0     0
1     0
2     0
3     0
4     0

In [10]:
X.drop(columns=['Geography', 'Gender'], inplace = True)

In [11]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [12]:
X = pd.concat([X, geography, gender], axis = True)

In [13]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [15]:
X_train.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9254          686   32       6       0.00              2          1   
1561          632   42       4  119624.60              2          1   
1670          559   24       3  114739.92              1          1   
6087          561   27       9  135637.00              1          1   
6669          517   56       9  142147.32              1          0   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
9254               1        179093.26        0      0     1  
1561               1        195978.86        1      0     1  
1670               0         85891.02        0      1     1  
6087               0        153080.40        0      0     0  
6669               0         39488.04        0      0     1

In [16]:
y_train.head()

9254    0
1561    0
1670    1
6087    1
6669    1
Name: Exited, dtype: int64

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
lr_X_train = X_train
lr_y_train = y_train

In [19]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [20]:
X_train

array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.57946723,
         1.73494238,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]])

In [21]:
X_train.shape

(8000, 11)

In [22]:
import torch.nn as nn

In [23]:
model = nn.Sequential()

In [24]:

import torch.nn.functional as F
import torch.optim as optim

In [25]:
model = nn.Sequential(
    nn.Linear(11, 7),  # Input layer, assuming 11 input features
    nn.ReLU(),  # Use ReLU as a layer
    nn.Linear(7, 6),
    nn.ReLU(),
    nn.Linear(6, 1),  # Output layer
    nn.Sigmoid()      # Apply Sigmoid for binary classification
)


# Optimizer (Equivalent to Keras' Adam)
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Loss Function (Equivalent to binary_crossentropy)
criterion = nn.BCELoss()

In [26]:
from torch.utils.data import DataLoader, TensorDataset

In [30]:
y_train = y_train.values

In [31]:
train_dataset = TensorDataset(torch.from_numpy(X_train).double(), torch.from_numpy(y_train))

In [32]:
# test_dataset = TensorDataset(torch.from_numpy(X_test).double())

In [33]:
train_loader = DataLoader(train_dataset, batch_size=100, shuffle=True)

In [34]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)  # Send the model to the device

Sequential(
  (0): Linear(in_features=11, out_features=7, bias=True)
  (1): ReLU()
  (2): Linear(in_features=7, out_features=6, bias=True)
  (3): ReLU()
  (4): Linear(in_features=6, out_features=1, bias=True)
  (5): Sigmoid()
)

In [ ]:
# ... data preparation with dataloader (code omitted for brevity)

for epoch in range(500):  # Example for 1000 epochs
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.float().to(device), y_batch.float().to(device)

        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass
        output = model(X_batch)

        # Loss calculation
        loss = criterion(output.squeeze(), y_batch.float())

        # Backpropagation
        loss.backward()

        # Weight Update
        optimizer.step()
    print(f'Finished epoch {epoch}, latest loss {loss}')

        # Add validation and logging if desired


In [189]:
X_test = torch.from_numpy(X_test).float().to(device)

In [191]:
with torch.no_grad():
    predictions = model(X_test)
    predicted_classes = (predictions >= 0.5).long()

print(predicted_classes)

tensor([[0],
        [0],
        [0],
        ...,
        [1],
        [0],
        [0]])


In [195]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(predicted_classes, y_test)
cm

array([[1520,  198],
       [  87,  195]])

In [198]:
from sklearn.metrics import accuracy_score
score = accuracy_score(predicted_classes, y_test)
score

0.8575

In [290]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [291]:
lr_X_train.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9254          686   32       6       0.00              2          1   
1561          632   42       4  119624.60              2          1   
1670          559   24       3  114739.92              1          1   
6087          561   27       9  135637.00              1          1   
6669          517   56       9  142147.32              1          0   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
9254               1        179093.26        0      0     1  
1561               1        195978.86        1      0     1  
1670               0         85891.02        0      1     1  
6087               0        153080.40        0      0     0  
6669               0         39488.04        0      0     1

In [292]:
lr_y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [293]:
lr.fit(lr_X_train, lr_y_train)
y_pred = lr.predict(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [295]:
cm = confusion_matrix(y_pred, y_test)
cm

array([[1031,   97],
       [ 576,  296]])

In [297]:
score = accuracy_score(y_pred, y_test)
score

0.6635

In [298]:
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier()

In [299]:
dc.fit(lr_X_train, lr_y_train)

DecisionTreeClassifier()

In [302]:
y_pred = dc.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [303]:
cm = confusion_matrix(y_pred, y_test)
cm

array([[ 332,  138],
       [1275,  255]])

In [304]:
score = accuracy_score(y_pred, y_test)
score

0.2935

In [305]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [307]:
y_ped =rfc.fit(lr_X_train, lr_y_train)

In [309]:
cm = confusion_matrix(y_pred, y_test)
cm

array([[ 332,  138],
       [1275,  255]])

In [310]:
score = accuracy_score(y_pred, y_test)
score

0.2935

In [45]:
model2 = nn.Sequential(
    nn.Linear(11, 7),  # Input layer, assuming 11 input features
    nn.LeakyReLU(),  # Use ReLU as a layer
    nn.Linear(7, 6),
    nn.LeakyReLU(),
    nn.Linear(6, 1),  # Output layer
    nn.Sigmoid()      # Apply Sigmoid for binary classification
)


# Optimizer (Equivalent to Keras' Adam)
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Loss Function (Equivalent to binary_crossentropy)
criterion = nn.BCELoss()

In [47]:
y_test_np = y_test.values

In [48]:
test_dataset_plot = TensorDataset(torch.from_numpy(X_test).double(), torch.from_numpy(y_test_np))

# Create a DataLoader for the test dataset
test_loader = DataLoader(test_dataset_plot, batch_size=100, shuffle=False)  # No need to shuffle for test data

In [49]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)  # Send the model to the device

Sequential(
  (0): Linear(in_features=11, out_features=7, bias=True)
  (1): ReLU()
  (2): Linear(in_features=7, out_features=6, bias=True)
  (3): ReLU()
  (4): Linear(in_features=6, out_features=1, bias=True)
  (5): Sigmoid()
)

In [52]:
# ... data preparation with dataloader (code omitted for brevity)
train_losses = []  # List to store training loss values
test_losses = []   # List to store test loss values


for epoch in range(10):  # Example for 1000 epochs
    epoch_train_losses = []  # List to store training loss values for current epoch
    epoch_test_losses = []   # List to store test loss values for current epoch

    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.float().to(device), y_batch.float().to(device)

        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass
        output = model(X_batch)

        # Loss calculation
        loss = criterion(output.squeeze(), y_batch.float())

        # Backpropagation
        loss.backward()

        # Weight Update
        optimizer.step()

        epoch_losses.append(loss.item())


    model.eval()  # Set model to evaluation mode
    with torch.no_grad():
        for X_test_batch, y_test_batch in test_loader:
            X_test_batch, y_test_batch = X_test_batch.float().to(device), y_test_batch.float().to(device)

            # Forward pass (test)
            output_test = model(X_test_batch)

            # Loss calculation (test)
            loss_test = criterion(output_test.squeeze(), y_test_batch.float())

            epoch_test_losses.append(loss_test.item())  # Append current test loss to epoch_test_losses list

    # Calculate average losses for current epoch
    # epoch_train_loss_avg = sum(epoch_train_losses) / len(epoch_train_losses)

    if len(epoch_train_losses) > 0:  # Check if list is not empty
      epoch_train_loss_avg = sum(epoch_train_losses) / len(epoch_train_losses)
    else:
      epoch_train_loss_avg = 0.0  # Or a suitable default value

    epoch_test_loss_avg = sum(epoch_test_losses) / len(epoch_test_losses)

    # Append average losses to train_losses and test_losses lists
    train_losses.append(epoch_train_loss_avg)
    test_losses.append(epoch_test_loss_avg)

    print(f'Finished epoch {epoch}, train loss: {epoch_train_loss_avg}, test loss: {epoch_test_loss_avg}')

        # Add validation and logging if desired


Finished epoch 0, train loss: 0.0, test loss: 0.33581323027610777
Finished epoch 1, train loss: 0.0, test loss: 0.33466840386390684
Finished epoch 2, train loss: 0.0, test loss: 0.33543070703744887
Finished epoch 3, train loss: 0.0, test loss: 0.3349223852157593
Finished epoch 4, train loss: 0.0, test loss: 0.33511715978384016
Finished epoch 5, train loss: 0.0, test loss: 0.33452803641557693
Finished epoch 6, train loss: 0.0, test loss: 0.3354372203350067
Finished epoch 7, train loss: 0.0, test loss: 0.334067103266716
Finished epoch 8, train loss: 0.0, test loss: 0.33432988822460175
Finished epoch 9, train loss: 0.0, test loss: 0.3339455649256706


In [328]:
X_test = torch.from_numpy(X_test).float().to(device)

TypeError: expected np.ndarray (got Tensor)

In [353]:
with torch.no_grad():
    predictions = model(X_test)
    predicted_classes = (predictions >= 0.5).long()

print(predicted_classes)

tensor([[0],
        [0],
        [0],
        ...,
        [1],
        [0],
        [0]])


In [330]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(predicted_classes, y_test)
cm

array([[1558,  230],
       [  49,  163]])

In [331]:
from sklearn.metrics import accuracy_score
score = accuracy_score(predicted_classes, y_test)
score

0.8605

In [332]:
print(model2)

Sequential(
  (0): Linear(in_features=11, out_features=7, bias=True)
  (1): LeakyReLU(negative_slope=0.01)
  (2): Linear(in_features=7, out_features=6, bias=True)
  (3): LeakyReLU(negative_slope=0.01)
  (4): Linear(in_features=6, out_features=1, bias=True)
  (5): Sigmoid()
)


In [334]:
from torchsummary import summary

summary(model2, input_size=(6,)) # Specify input shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x6 and 11x7)